### ISSUE TITLE
Don't std::move local return values

### ISSUE THREAD

**Issue by lorenzhs** [haptork/easyLambda#1]
It's a bad idea to apply `std::move` when returning a local object. Scott Meyer says: "Never apply `std::move` or `std::forward` to local objects if they would otherwise be eligible for the return value optimization" (Effective Modern C++)

The idea is that the compiler _can_ optimize away the copy if you return by value, but if it can't, it _must_ move. If you apply `std::move` then it has to move in either way. You're preventing RVO from happening.

I saw this in a few places around the code: https://github.com/haptork/easyLambda/search?q="return+std%3A%3Amove"&type=Code

**Comment by haptork** [comment]
Thanks for clarifying on this long dwelling confusion I had. It is mostly in places where shared_ptr of an object is being returned so shouldn't break anything at all.

I remembered reading or watching something on this but was a bit confused. At some moment I settled with moving and thought RVO will happen with `std::move` as well. I'm tempted to think how `std::move` can really stop RVO in all cases.

**Comment by lorenzhs** [comment]
Yeah it's super confusing. I have a print-out of all the things to remember from Effective Modern C++ on the wall behind me, that definitely helps :)

**Comment by haptork** [comment]
It is straight forward to remove std::move in cases where a shared_ptr is being returned as in build() of MapExpr, ReduceExpr, ReduceBuilder etc.

There are two cases where I'm not pretty sure about this:
1. When a MapBuilder/ReduceBuilder is being returned, since they have a function object that can be move only. I want to be sure that ROV will also make compiler not throw an error about no copy constructor. I think there shouldn't be a problem and I can check it by passing some non-copiable object.
2. In runResult of DataFlowExpr a vector of rows is returned, since the vector can be big, I will first make sure that ROV is happening and then remove std::move(). 

Any suggestions are welcome.

**Comment by lorenzhs** [comment]
Regarding point 1, if the compiler can't RVO then it has to move, so in the best case nothing happens, and in the worst case a move happens (if a `noexcept` move constructor exists, otherwise a copy happens). Should be safe. Same about the big vector. I know it's scary :) The relevant section in the standard ([C++14 standard draft](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf)) are §12.8, paragraph 31 (page 294 in the pdf page numbering). There's an example on the page after. Paragraph 32 is the bit where it mandates a move if it can't copy, but it's phrased in so much legalese ("...overload resolution to select the constructor for the copy is first performed as if the object were designated by an rvalue.") that I had to look twice even though I knew it was there. It's much more understandable in item 25 (page 174 and 175) in Scott Meyers' book.

**Comment by haptork** [comment]
Thanks a tons. Removed std::move() from all the local return values.
